In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import skew
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv')    #original dataframe
test_df = pd.read_csv('test.csv')

#create a copy of dataframe for data processing and data cleaning
df_new = df.copy()


print(df_new.describe())
print("\n")


#print the datatypes in the dataframe
print("Datatypes of columns: \n" , df_new.dtypes)


#print the first five values from the dataset
print("Print the first five rows of the dataset: \n" , df_new.head())

                 id  sleep_duration     heart_rate            bmi  \
count  690088.00000   614089.000000  682255.000000  676190.000000
mean   345043.50000        6.992597      75.096504      22.984925
std    199211.39062        1.215407       8.175106       2.481787
min         0.00000        3.000000      50.000000      16.000000
25%    172521.75000        6.160000      69.400000      21.320000
50%    345043.50000        6.990000      75.100000      22.990000
75%    517565.25000        7.810000      80.700000      24.660000
max    690087.00000       10.000000     107.700000      34.820000

       calorie_expenditure     step_count  exercise_duration   water_intake
count        637235.000000  676172.000000      683187.000000  646611.000000
mean           2226.084931    8615.953050          38.751456       2.188542
std             347.532098    3929.399831          14.742189       0.518489
min            1200.000000    1002.000000           0.000000       0.500000
25%            2053.000000    5389.000000          29.200000       1.840000
50%            2241.000000    8856.000000          39.400000       2.170000
75%            2456.000000   12114.000000          49.400000       2.500000
max            3580.000000   14999.000000          99.800000       4.720000


Datatypes of columns:
 id                           int64
health_condition            object
sleep_duration             float64
heart_rate                 float64
bmi                        float64
calorie_expenditure        float64
step_count                 float64
exercise_duration          float64
water_intake               float64
diet_type                   object
stress_level                object
sleep_quality               object
physical_activity_level     object
smoking_alcohol             object
gender                      object
dtype: object
Print the first five rows of the dataset:
    id health_condition  sleep_duration  heart_rate    bmi  \
0   0        unhealthy            5.22        70.6  25.66
1   1          at-risk            5.53        71.3  25.84
2   2        unhealthy            5.29        75.4  24.54
3   3        unhealthy            4.70        77.2  23.13
4   4          at-risk            7.23        73.4  28.44

   calorie_expenditure  step_count  exercise_duration  water_intake diet_type  \
0               2174.0      1326.0               19.8          1.86       veg
1               1966.0      9891.0               49.9          1.26   non-veg
2               2688.0     14216.0               38.1          1.60       veg
3               2630.0      7174.0               59.9          2.02       veg
4               2560.0      6584.0               46.0          2.25       veg

  stress_level sleep_quality physical_activity_level smoking_alcohol  gender
0         high       average               sedentary             yes  female
1          low       average                moderate             yes   other
2         high          poor                  active             yes    male
3         high       average                  active      occasional  female
4          NaN       average               sedentary             NaN    male

In [3]:
# display the first 5 rows
df_new.head(5)

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,0,unhealthy,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,high,average,sedentary,yes,female
1,1,at-risk,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,low,average,moderate,yes,other
2,2,unhealthy,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,high,poor,active,yes,male
3,3,unhealthy,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,veg,high,average,active,occasional,female
4,4,at-risk,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,veg,NaN,average,sedentary,NaN,male

In [4]:
# print unique values of the ordinal columns

smoking_alcohol = df['smoking_alcohol'].unique()
physical_activity_level = df['physical_activity_level'].unique()
sleep_quality = df['sleep_quality'].unique()
stress_level = df['stress_level'].unique()

print(smoking_alcohol)
print(physical_activity_level)
print(sleep_quality)
print(stress_level)

['yes' 'occasional' nan 'no']
['sedentary' 'moderate' 'active' nan]
['average' 'poor' nan 'good']
['high' 'low' nan 'medium']

In [5]:
# count the number of null values for each row
no_of_null_values = df_new.isna().sum()
print("Count of Null values\n", no_of_null_values)
print("\n")

# count the percentage of null values
null_percentage = (df_new.isna().sum()/ len(df_new)) * 100
print("Percentage of null values in each column is : \n" , null_percentage)
print("\n")

Count of Null values
 id                             0
health_condition               0
sleep_duration             75999
heart_rate                  7833
bmi                        13898
calorie_expenditure        52853
step_count                 13916
exercise_duration           6901
water_intake               43477
diet_type                   6901
stress_level               82811
sleep_quality              58331
physical_activity_level    36621
smoking_alcohol            28582
gender                     21373
dtype: int64


Percentage of null values in each column is :
 id                          0.000000
health_condition            0.000000
sleep_duration             11.012943
heart_rate                  1.135073
bmi                         2.013946
calorie_expenditure         7.658878
step_count                  2.016554
exercise_duration           1.000017
water_intake                6.300211
diet_type                   1.000017
stress_level               12.000064
sleep_quality               8.452690
physical_activity_level     5.306715
smoking_alcohol             4.141791
gender                      3.097141
dtype: float64

In [6]:
df_new.duplicated().sum()

np.int64(0)

Handle Numerical Missing Values in the Dataset

In [7]:
# Check the skewness of columns with high percentage of missing values i.e sleep_duration
sleep_duration = skew(df_new["sleep_duration"].dropna())
print("Skewness of the sleep duration:" ,  sleep_duration)

# Handling missing values of the above column through mean since the skewness is close to 0
df_new['sleep_duration'] == df_new['sleep_duration'].fillna(df_new['sleep_duration'].mean(), inplace = True)


# Replace all the missing values with mean
df_new['heart_rate'] = df_new['heart_rate'].fillna(df_new['heart_rate'].mean())

df_new['bmi'] = df_new['bmi'].fillna(df_new['bmi'].mean())

df_new['calorie_expenditure'] = df_new['calorie_expenditure'].fillna(df_new['calorie_expenditure'].mean())

df_new['step_count'] = df_new['step_count'].fillna(df_new['step_count'].mean())

df_new['exercise_duration'] = df_new['exercise_duration'].fillna(df_new['exercise_duration'].mean())

df_new['water_intake'] = df_new['water_intake'].fillna(df_new['water_intake'].mean())

Skewness of the sleep duration: -0.008232318890284017

In [8]:
df_new.isna().sum()     #check the number of null values in a column

id                             0
health_condition               0
sleep_duration                 0
heart_rate                     0
bmi                            0
calorie_expenditure            0
step_count                     0
exercise_duration              0
water_intake                   0
diet_type                   6901
stress_level               82811
sleep_quality              58331
physical_activity_level    36621
smoking_alcohol            28582
gender                     21373
dtype: int64

In [9]:
# Replace the missing values for categorical columns
# Classifying the different types of column values
# gender - nominal
# smoking_alcohol - ordinal
# physical activity level - ordinal
# sleep quality - ordinal
# stress level - ordinal
# diet type - nominal

In [10]:
import pandas as pd
import numpy as np


# Calculate the percentage of missing values in categorical columns
print(null_percentage)

id                          0.000000
health_condition            0.000000
sleep_duration             11.012943
heart_rate                  1.135073
bmi                         2.013946
calorie_expenditure         7.658878
step_count                  2.016554
exercise_duration           1.000017
water_intake                6.300211
diet_type                   1.000017
stress_level               12.000064
sleep_quality               8.452690
physical_activity_level     5.306715
smoking_alcohol             4.141791
gender                      3.097141
dtype: float64

In [11]:
df_new.isna().sum()

id                             0
health_condition               0
sleep_duration                 0
heart_rate                     0
bmi                            0
calorie_expenditure            0
step_count                     0
exercise_duration              0
water_intake                   0
diet_type                   6901
stress_level               82811
sleep_quality              58331
physical_activity_level    36621
smoking_alcohol            28582
gender                     21373
dtype: int64

Handle Categorical Missing Values in the Dataset

In [12]:
# replace the missing value with mode for ordinal columns
ordinal_cols = [
    "stress_level",
    "sleep_quality",
    "physical_activity_level",
    "smoking_alcohol"
]

for col in ordinal_cols:
    df_new[col] = df_new[col].fillna(df_new[col].mode()[0])


# impute values for diet_type and gender columns

# Fill using the first mode value found


df_new['diet_type'] = df_new['diet_type'].fillna(df_new['diet_type'].mode()[0])
df_new['gender'] = df_new['gender'].fillna(df_new['gender'].mode()[0])

In [13]:
df_new.isna().sum()

id                         0
health_condition           0
sleep_duration             0
heart_rate                 0
bmi                        0
calorie_expenditure        0
step_count                 0
exercise_duration          0
water_intake               0
diet_type                  0
stress_level               0
sleep_quality              0
physical_activity_level    0
smoking_alcohol            0
gender                     0
dtype: int64

ORDINAL ENCODING FOR CATEGORICAL COLUMNS

In [14]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# 1. ORDINAL ENCODING
# Create mappings

smoking_mapping = {
    "no": 0,
    "occasional": 1,
    "yes": 2
}

physical_activity_mapping = {
    "sedentary": 0,
    "moderate": 1,
    "active": 2
}

sleep_quality_mapping = {
    "poor": 0,
    "average": 1,
    "good": 2
}

stress_level_mapping = {
    "low": 0,
    "medium": 1,
    "high": 2
}

# Define the columns to be ordinal encoded
columns_to_encode = ["smoking_alcohol", "physical_activity_level", "sleep_quality", "stress_level"]

for col in columns_to_encode:
    # Revert to original string values from 'df' (which should hold the raw categories)
    df_new[col] = df[col]
    # Fill any NaNs using the mode of the current df_new column (which now contains original strings)
    df_new[col] = df_new[col].fillna(df_new[col].mode()[0])

df_new[columns_to_encode] = df_new[columns_to_encode].astype(str)

# Ordinal encoder
# Convert dictionaries of mapping to list
# the encoder receives list of lists
encoder = OrdinalEncoder(categories = [list(smoking_mapping.keys()), list(physical_activity_mapping.keys()), list(sleep_quality_mapping.keys()), list(stress_level_mapping.keys())])

df_new[columns_to_encode] = encoder.fit_transform(df_new[columns_to_encode])

#print the first few values in the column
print(df_new.head())

   id health_condition  sleep_duration  heart_rate    bmi  \
0   0        unhealthy            5.22        70.6  25.66
1   1          at-risk            5.53        71.3  25.84
2   2        unhealthy            5.29        75.4  24.54
3   3        unhealthy            4.70        77.2  23.13
4   4          at-risk            7.23        73.4  28.44

   calorie_expenditure  step_count  exercise_duration  water_intake diet_type  \
0               2174.0      1326.0               19.8          1.86       veg
1               1966.0      9891.0               49.9          1.26   non-veg
2               2688.0     14216.0               38.1          1.60       veg
3               2630.0      7174.0               59.9          2.02       veg
4               2560.0      6584.0               46.0          2.25       veg

   stress_level  sleep_quality  physical_activity_level  smoking_alcohol  \
0           2.0            1.0                      0.0              2.0
1           0.0            1.0                      1.0              2.0
2           2.0            0.0                      2.0              2.0
3           2.0            1.0                      2.0              1.0
4           1.0            1.0                      0.0              2.0

   gender
0  female
1   other
2    male
3  female
4    male

ONE-HOT ENCODING FOR CATEGORICAL COLUMNS

In [15]:
# 2. ONE-HOT ENCODING


nominal_columns = [
    "gender",
    "diet_type"
]


preprocessor = ColumnTransformer(
    transformers=[
        (
            "onehot",
            OneHotEncoder(
                sparse_output=False,
                handle_unknown="ignore"
            ),
            nominal_columns
        )
    ],
    remainder="passthrough"
)



# 3. APPLY TRANSFORMATION

encoded_array = preprocessor.fit_transform(df_new)



# 4. CREATE FINAL DATAFRAME

encoded_columns = preprocessor.get_feature_names_out()

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoded_columns,
    index=df_new.index
)


print(encoded_df.head())

print("\nShape of encoded dataframe:")
print(encoded_df.shape)

  onehot__gender_female onehot__gender_male onehot__gender_other  \
0                   1.0                 0.0                  0.0
1                   0.0                 0.0                  1.0
2                   0.0                 1.0                  0.0
3                   1.0                 0.0                  0.0
4                   0.0                 1.0                  0.0

  onehot__diet_type_balanced onehot__diet_type_non-veg onehot__diet_type_veg  \
0                        0.0                       0.0                   1.0
1                        0.0                       1.0                   0.0
2                        0.0                       0.0                   1.0
3                        0.0                       0.0                   1.0
4                        0.0                       0.0                   1.0

  remainder__id remainder__health_condition remainder__sleep_duration  \
0             0                   unhealthy                      5.22
1             1                     at-risk                      5.53
2             2                   unhealthy                      5.29
3             3                   unhealthy                       4.7
4             4                     at-risk                      7.23

  remainder__heart_rate remainder__bmi remainder__calorie_expenditure  \
0                  70.6          25.66                         2174.0
1                  71.3          25.84                         1966.0
2                  75.4          24.54                         2688.0
3                  77.2          23.13                         2630.0
4                  73.4          28.44                         2560.0

  remainder__step_count remainder__exercise_duration remainder__water_intake  \
0                1326.0                         19.8                    1.86
1                9891.0                         49.9                    1.26
2               14216.0                         38.1                     1.6
3                7174.0                         59.9                    2.02
4                6584.0                         46.0                    2.25

  remainder__stress_level remainder__sleep_quality  \
0                     2.0                      1.0
1                     0.0                      1.0
2                     2.0                      0.0
3                     2.0                      1.0
4                     1.0                      1.0

  remainder__physical_activity_level remainder__smoking_alcohol
0                                0.0                        2.0
1                                1.0                        2.0
2                                2.0                        2.0
3                                2.0                        1.0
4                                0.0                        2.0

Shape of encoded dataframe:
(690088, 19)

In [16]:
print(encoded_df.shape[1])    #print the number of columns

19

In [17]:
print(encoded_df.columns)

Index(['onehot__gender_female', 'onehot__gender_male', 'onehot__gender_other',
       'onehot__diet_type_balanced', 'onehot__diet_type_non-veg',
       'onehot__diet_type_veg', 'remainder__id', 'remainder__health_condition',
       'remainder__sleep_duration', 'remainder__heart_rate', 'remainder__bmi',
       'remainder__calorie_expenditure', 'remainder__step_count',
       'remainder__exercise_duration', 'remainder__water_intake',
       'remainder__stress_level', 'remainder__sleep_quality',
       'remainder__physical_activity_level', 'remainder__smoking_alcohol'],
      dtype='object')

In [18]:
# Check whether there are any null values
encoded_df.isnull().sum()

onehot__gender_female                 0
onehot__gender_male                   0
onehot__gender_other                  0
onehot__diet_type_balanced            0
onehot__diet_type_non-veg             0
onehot__diet_type_veg                 0
remainder__id                         0
remainder__health_condition           0
remainder__sleep_duration             0
remainder__heart_rate                 0
remainder__bmi                        0
remainder__calorie_expenditure        0
remainder__step_count                 0
remainder__exercise_duration          0
remainder__water_intake               0
remainder__stress_level               0
remainder__sleep_quality              0
remainder__physical_activity_level    0
remainder__smoking_alcohol            0
dtype: int64

In [19]:
encoded_df.info()
encoded_df.duplicated().sum()   #check for duplicates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690088 entries, 0 to 690087
Data columns (total 19 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   onehot__gender_female               690088 non-null  object
 1   onehot__gender_male                 690088 non-null  object
 2   onehot__gender_other                690088 non-null  object
 3   onehot__diet_type_balanced          690088 non-null  object
 4   onehot__diet_type_non-veg           690088 non-null  object
 5   onehot__diet_type_veg               690088 non-null  object
 6   remainder__id                       690088 non-null  object
 7   remainder__health_condition         690088 non-null  object
 8   remainder__sleep_duration           690088 non-null  object
 9   remainder__heart_rate               690088 non-null  object
 10  remainder__bmi                      690088 non-null  object
 11  remainder__calorie_expenditure      690088 non-null  object
 12  remainder__step_count               690088 non-null  object
 13  remainder__exercise_duration        690088 non-null  object
 14  remainder__water_intake             690088 non-null  object
 15  remainder__stress_level             690088 non-null  object
 16  remainder__sleep_quality            690088 non-null  object
 17  remainder__physical_activity_level  690088 non-null  object
 18  remainder__smoking_alcohol          690088 non-null  object
dtypes: object(19)
memory usage: 100.0+ MB

np.int64(0)

In [20]:
# Check for class distribution
print(df_new["health_condition"].value_counts())

print(df_new["health_condition"].value_counts(normalize=True))

health_condition
at-risk      592561
unhealthy     57724
fit           39803
Name: count, dtype: int64
health_condition
at-risk      0.858675
unhealthy    0.083647
fit          0.057678
Name: proportion, dtype: float64

In [21]:
#Implementing the train and test set
X = encoded_df.drop(columns = ['remainder__id','remainder__health_condition'])
Y = encoded_df['remainder__health_condition']


from sklearn.model_selection import train_test_split

X_train, X_valid, Y_train, Y_valid = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

# Print shapes using .shape attribute (not a method)
print("x_train shape:", X_train.shape)
print("y_train shape:", Y_train.shape)


#Implement a random forest classifier
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    random_state=42,
    n_estimators=200
)

model.fit(X_train, Y_train)

x_train shape: (552070, 17)
y_train shape: (552070,)

RandomForestClassifier(n_estimators=200, random_state=42)

In [22]:

from sklearn.metrics import balanced_accuracy_score

Y_pred = model.predict(X_valid)

score = balanced_accuracy_score(Y_valid, Y_pred)

print(score)

0.8530192272404588

In [23]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(Y_valid, Y_pred))
print(confusion_matrix(Y_valid, Y_pred))

              precision    recall  f1-score   support

     at-risk       0.97      1.00      0.98    118512
         fit       0.95      0.79      0.87      7961
   unhealthy       0.98      0.77      0.86     11545

    accuracy                           0.97    138018
   macro avg       0.96      0.85      0.90    138018
weighted avg       0.97      0.97      0.96    138018

[[118013    299    200]
 [  1608   6326     27]
 [  2656     15   8874]]

Utilizing the testing set to predict the values

In [29]:
Y_test = test_df.copy()

# 1. Handle Numerical Missing Values (using means from df_new, which was already imputed)
Y_test['sleep_duration'] = Y_test['sleep_duration'].fillna(df_new['sleep_duration'].mean())
Y_test['heart_rate'] = Y_test['heart_rate'].fillna(df_new['heart_rate'].mean())
Y_test['bmi'] = Y_test['bmi'].fillna(df_new['bmi'].mean())
Y_test['calorie_expenditure'] = Y_test['calorie_expenditure'].fillna(df_new['calorie_expenditure'].mean())
Y_test['step_count'] = Y_test['step_count'].fillna(df_new['step_count'].mean())
Y_test['exercise_duration'] = Y_test['exercise_duration'].fillna(df_new['exercise_duration'].mean())
Y_test['water_intake'] = Y_test['water_intake'].fillna(df_new['water_intake'].mean())

# 2. Handle Categorical Missing Values (using modes from the original training dataframe `df`)
ordinal_cols = ["stress_level", "sleep_quality", "physical_activity_level", "smoking_alcohol"]
for col in ordinal_cols:
    # Use the mode from the original training dataframe (df) to fill NaNs in Y_test
    Y_test[col] = Y_test[col].fillna(df[col].mode()[0])

Y_test['diet_type'] = Y_test['diet_type'].fillna(df['diet_type'].mode()[0])
Y_test['gender'] = Y_test['gender'].fillna(df['gender'].mode()[0])

# 3. Ordinal Encoding (using the already fitted encoder)
columns_to_encode = ["smoking_alcohol", "physical_activity_level", "sleep_quality", "stress_level"]
# Ensure the columns are of string type before ordinal encoding
Y_test[columns_to_encode] = Y_test[columns_to_encode].astype(str)
Y_test[columns_to_encode] = encoder.transform(Y_test[columns_to_encode])

# 4. One-Hot Encoding (using the already fitted preprocessor)
# Add a dummy 'health_condition' column to Y_test to match the columns the preprocessor was fitted on.
# The actual values do not matter as this column will be filtered out from the final features.
Y_test['health_condition'] = 'placeholder'
test_encoded_array = preprocessor.transform(Y_test)

# Get all feature names from the fitted preprocessor
all_encoded_test_feature_names = preprocessor.get_feature_names_out()

# Create a DataFrame with all 19 columns initially
temp_test_encoded_df = pd.DataFrame(
    test_encoded_array,
    columns=all_encoded_test_feature_names,
    index=Y_test.index
)

# 5. Drop the 'id' and 'health_condition' columns to match the training features (X_train)
X_test_processed = temp_test_encoded_df.drop(columns=['remainder__id', 'remainder__health_condition'])

y_test_predictions = model.predict(X_test_processed)

In [42]:
# Print the test results
print(y_test_predictions)

predicted_values = pd.DataFrame(X_test_processed)

# Add the original 'id' column from test_df to predicted_values BEFORE selecting columns
predicted_values['remainder__id'] = test_df['id']

predicted_values['remainder_health_condition'] = y_test_predictions
predicted_values.head()


#final dataframe
final_predicted_df = predicted_values[['remainder__id', 'remainder_health_condition']]
print(final_predicted_df.head(5))

['unhealthy' 'at-risk' 'at-risk' ... 'at-risk' 'at-risk' 'unhealthy']
   remainder__id remainder_health_condition
0         690088                  unhealthy
1         690089                    at-risk
2         690090                    at-risk
3         690091                    at-risk
4         690092                  unhealthy

In [44]:
#Download the dataframe as a CSV file
final_predicted_df.to_csv('submission.csv', index=False)

# 2. Trigger browser download to your local machine
from google.colab import files
files.download('submission.csv')